name: Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: '0,30 * * * *'
  push:
    branches: [ master ]

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: corepack enable && pnpm i

      - name: Fetch api data
        env:
          XIAOTIE_TOKEN: ${{ secrets.XIAOTIE_TOKEN }}
        run: npm run start

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'chore: fetch data [ci skip]'
          add: "data"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
